### ISSUE TITLE
Latency dashboard showing inconsistent data

### ISSUE THREAD

**Issue by faiz0210** [aerospike/aerospike-monitoring#18] opened 2020-05-07 17:39 UTC
Hi Team,

Latency dashboard is showing inconsistent data. We have both AMC and asprom enabled in our system. Data is coming properly on them but aerospike-prometheus-exporter is showing inconsistent data. Screenshot shared below:

Aerospike Prometheus Exporter:

![image001](https://user-images.githubusercontent.com/37917624/81326510-93203d80-90b7-11ea-818d-c7c46af584a2.png)

Asprom Exporter:

![image002](https://user-images.githubusercontent.com/37917624/81326557-a7643a80-90b7-11ea-8a55-6d00c81912ee.png)

Aerospike version: 4.8.0.8

Let me know if you need further information on this.

**Comment by spkesan** [comment] 2020-05-18 20:48
@faiz0210 
Are you able to observe this consistently?
Did you also check on prometheus graph if the values are absent there?
Note that the dots are just due to grafana. You can get them connected.
But I'm looking at the gaps between the values in your grafana dashboard which is varying (increasing). It should be close to `scrape_interval` on prometheus server. I believe your `scrape_interval` is 15s ?

**Comment by faiz0210** [comment] 2020-05-18 22:09
Yes this behaviour is consistent and it's the same for grafana and prometheus.
Although for one of the namespace graph is a bit consistent, even though job is same for all nodes and cluster.
Query I'm using for asprom is aerospike_latency_write{instance=~"$ip",job=~"$job",namespace=~"$ns"}.
I hope both these queries interpret the same output.
and yes scrape_interval is 15s.

**Comment by spkesan** [comment] 2020-05-19 00:11
@faiz0210 
I have few more questions (as I'm not able to reproduce this):

1. Are you using two different monitoring setup? One with [asprom](https://github.com/alicebob/asprom) (with your own created grafana dashboards) and another with [aerospike-prometheus-exporter](https://github.com/aerospike/aerospike-prometheus-exporter)(with dashboards from [aerospike-monitoring](https://github.com/aerospike/aerospike-monitoring) repository)

- Let's address the two exporters as - **asprom** and **aerospike-prometheus-exporter** separately.

- Also, don't use dashboards interchangeably with these two different exporters, even PromQL queries because even the metric names are different among these exporters. 

2. **aerospike-prometheus-exporter** sends latency information once every 10s (default [hist-track-slice](https://www.aerospike.com/docs/reference/configuration/index.html#hist-track-slice)). 

- For every scrape, aerospike-prometheus-exporter gets the new "latency:" output from the aerospike server, and compares the timestamp in the latency data to the previous scrape (the timestamp would be same for 10s or hist-track-slice). If they are different, it would send the latency data to prometheus.

I believe it may be due to this.  Can you describe your setup ?  Are there multiple Prometheus servers scraping the same **aerospike-prometheus-exporter** target ?

**Comment by spkesan** [comment] 2020-05-19 11:13
@faiz0210 I have done a fix on [aerospike/aerospike-prometheus-exporter](https://github.com/aerospike/aerospike-prometheus-exporter) to remove the timestamp check on latency data so that the metric is sent for every scrape. This will solve the issue. Can you try to build the exporter again and verify this.
https://github.com/aerospike/aerospike-monitoring#installing-aerospike-prometheus-exporter

**Comment by faiz0210** [comment] 2020-05-19 11:31
@spkesan Yes, I have both asprom and aerospike-prometheus-exporter running on different ports. Single prometheus server scraping the two exporters.

As of now, I can't remove asprom, reason being all our alerting is setup through Grafana and it doesn't support alerting when variables are used in the queries. I'll have to create my own dashboard for aerospike-prometheus-exporter without any variables, then only I would be able remove asprom.

Allow me a couple of days, I'll build the exporter with latest changes and share the results.

**Comment by faiz0210** [comment] 2020-05-20 11:50
Enabled it on one of the nodes and latency graph is looking good now.

**Comment by spkesan** [comment] 2020-05-20 12:35
Great! Thanks @faiz0210 for verifying. I'll go ahead and close this issue.

**Closed by spkesan** 2020-05-20 12:35 UTC
